name: 'Set environment variables'
description: 'Configures environment variables for a workflow'

inputs:
  varFilePath:
    description: 'File path to variable file or directory.'
    required: false
    default: ./.github/variables/*

runs:
  using: "composite"
  steps:
    - run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash