/// Flutter icons AppIconsAdditional
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconsAdditional
///      fonts:
///       - asset: fonts/AppIconsAdditional.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIconsAdditional {
  AppIconsAdditional._();

  static const _kFontFam = 'AppIconsAdditional';
  static const String? _kFontPkg = null;

  static const IconData schedule = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData immersion = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service_civique = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
