class Drawables {
  Drawables._();

  static String _assets = "assets/";
  static String _svg = ".svg";
  static String _png = ".png";
  static String icLogo = _assets + "ic_logo" + _svg;
  static String icMenuHome = _assets + "ic_menu_home" + _svg;
  static String icMenuAction = _assets + "ic_menu_action" + _svg;
  static String icMenuChat = _assets + "ic_menu_chat" + _svg;
  static String icMenuPlus = _assets + "ic_menu_plus" + _svg;
  static String icMenuSelectedBullet = _assets + "ic_menu_selected_bullet" + _svg;
  static String icSearchingBar = _assets + "ic_searching" + _svg;
  static String icBadge = _assets + "ic_badge" + _svg;
  static String icHeart = _assets + "ic_heart" + _svg;
  static String icHeartFull = _assets + "ic_heart_full" + _svg;
  static String icAdd = _assets + "ic_add" + _svg;
  static String icShare = _assets + "ic_share" + _svg;
  static String icPlace = _assets + "ic_place" + _svg;
  static String icContract = _assets + "ic_contract" + _svg;
  static String icSalary = _assets + "ic_salary" + _svg;
  static String icTime = _assets + "ic_time" + _svg;
  static String icOnePoint = _assets + "ic_one_point" + _svg;
  static String icTwoPoints = _assets + "ic_two_points" + _svg;
  static String icThreePoints = _assets + "ic_three_points" + _svg;
  static String icImportant = _assets + "ic_important" + _svg;
  static String icInfo = _assets + "ic_info" + _svg;
  static String icRedirection = _assets + "ic_redirection" + _svg;
  static String icPaperPlane = _assets + "ic_paper_plane" + _svg;
  static String icCongratulations = _assets + "ic_congratulations" + _svg;
  static String icClose = _assets + "ic_close" + _svg;
  static String icCalendar = _assets + "ic_calendar" + _svg;
  static String icClock = _assets + "ic_clock" + _svg;
  static String icMail = _assets + "ic_mail" + _svg;
  static String icFilter = _assets + "ic_filter" + _svg;
  static String icChevronRight = _assets + "chevron_right" + _svg;
  static String icNoContent = _assets + "ic_no_content" + _svg;
  static String icChevronLeft = _assets + "chevron_left" + _svg;
  static String icLaunch = _assets + "launch" + _svg;
  static String icDone = _assets + "ic_done" + _svg;
  static String icEuro = _assets + "ic_euro" + _svg;
  static String icFlash = _assets + "ic_flash" + _svg;
  static String icOnboardingChat = _assets + "ic_onboarding_chat" + _svg;
  static String icSearch = _assets + "ic_search" + _svg;
  static String icPeople = _assets + "ic_people" + _svg;
  static String puzzle = _assets + "puzzle" + _svg;

  static String passEmploiLogo = _assets + "logo_pass_emploi_white" + _svg;
  static String icAlert = _assets + "ic_alert" + _svg;
  static String icUnJeuneUneSolution = _assets + "un_jeune_une_solution_logo" + _png;
  static String jeuneEntree = _assets + "jeune_home" + _png;
  static String conversation = _assets + "conversation" + _svg;
  static String icEmptyOffres = _assets + "ic_empty_offres" + _svg;
}
