# Doc can be [found here](https://dart.dev/guides/language/analysis-options)
include:
  package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_return: error
    dead_code: error
    unused_element: error
    always_declare_return_types: error
    prefer_double_quotes: error
    prefer_final_fields: error
    prefer_final_locals: error
    sort_child_properties_last: error
    use_decorated_box: error
    constant_identifier_names: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_constructors_in_immutables: ignore
    use_key_in_widget_constructors: ignore