import 'package:equatable/equatable.dart';
import 'package:pass_emploi_app/models/tutorial/tutorial_data.autogenerated.dart';

class Tutorial extends Equatable {
  static const String version = TutorialData.version;

  static List<Tutorial> milo = TutorialData.milo;

  static List<Tutorial> poleEmploi = TutorialData.pe;

  final String title;
  final String description;
  final String image;

  Tutorial({required this.title, required this.description, required this.image});

  @override
  List<Object?> get props => [title, description, image];
}
