class Metier {
  final String codeRome;
  final String libelle;

  Metier(this.codeRome, this.libelle);

  static List<Metier> values = [
    Metier("G1404", "Management d'établissement de restauration collective"),
    Metier("G1501", "Personnel d'étage"),
    Metier("G1502", "Personnel polyvalent d'hôtellerie"),
    Metier("G1503", "Management du personnel d'étage"),
    Metier("F1101", "Architecture du BTP et du paysage"),
    Metier("F1102", "Conception - aménagement d'espaces intérieurs"),
    Metier("F1104", "Dessin BTP et paysage"),
    Metier("F1201", "Conduite de travaux du BTP et de travaux paysagers"),
    Metier("F1106", "Ingénierie et études du BTP"),
    Metier("F1204", "Qualité Sécurité Environnement et protection santé du BTP"),
    Metier("F1301", "Conduite de grue"),
    Metier("F1302", "Conduite d'engins de terrassement et de carrière"),
    Metier("F1402", "Extraction solide"),
    Metier("F1602", "Électricité bâtiment"),
    Metier("F1502", "Montage de structures métalliques"),
    Metier("F1401", "Extraction liquide et gazeuse"),
    Metier("F1605", "Montage de réseaux électriques et télécoms"),
    Metier("F1611", "Réalisation et restauration de façades"),
    Metier("F1613", "Travaux d'étanchéité et d'isolation"),
    Metier("F1702", "Construction de routes et voies"),
    Metier("F1612", "Taille et décoration de pierres"),
    Metier("F1607", "Pose de fermetures menuisées"),
    Metier("F1610", "Pose et restauration de couvertures"),
    Metier("G1605", "Plonge en restauration"),
    Metier("G1403", "Gestion de structure de loisirs ou d'hébergement touristique"),
    Metier("G1102", "Promotion du tourisme local"),
    Metier("G1303", "Vente de voyages"),
    Metier("F1103", "Contrôle et diagnostic technique du bâtiment"),
    Metier("F1203", "Direction et ingénierie d'exploitation de gisements et de carrières"),
    Metier("F1107", "Mesures topographiques"),
    Metier("F1108", "Métré de la construction"),
    Metier("F1105", "Études géologiques"),
    Metier("F1202", "Direction de chantier du BTP"),
    Metier("F1503", "Réalisation - installation d'ossatures bois"),
    Metier("F1501", "Montage de structures et de charpentes bois"),
    Metier("D1403", "Relation commerciale auprès de particuliers"),
    Metier("F1601", "Application et décoration en plâtre, stuc et staff"),
    Metier("F1703", "Maçonnerie"),
    Metier("G1201", "Accompagnement de voyages, d'activités culturelles ou sportives"),
    Metier("F1706", "Préfabrication en béton industriel"),
    Metier("F1704", "Préparation du gros oeuvre et des travaux publics"),
    Metier("F1705", "Pose de canalisations"),
    Metier("F1606", "Peinture en bâtiment"),
    Metier("F1604", "Montage d'agencements"),
    Metier("F1603", "Installation d'équipements sanitaires et thermiques"),
    Metier("G1202", "Animation d'activités culturelles ou ludiques"),
    Metier("F1701", "Construction en béton"),
    Metier("G1402", "Management d'hôtel-restaurant"),
    Metier("G1302", "Optimisation de produits touristiques"),
    Metier("G1401", "Assistance de direction d'hôtel-restaurant"),
    Metier("F1609", "Pose de revêtements souples"),
    Metier("G1206", "Personnel technique des jeux"),
    Metier("F1608", "Pose de revêtements rigides"),
    Metier("G1204", "Éducation en activités sportives"),
    Metier("G1101", "Accueil touristique"),
    Metier("G1203", "Animation de loisirs auprès d'enfants ou d'adolescents"),
    Metier("G1702", "Personnel du hall"),
    Metier("H1205", "Études - modèles en industrie des matériaux souples"),
    Metier("H1102", "Management et ingénierie d'affaires"),
    Metier("H1203", "Conception et dessin produits mécaniques"),
    Metier("H1206", "Management et ingénierie études, recherche et développement industriel"),
    Metier("H1204", "Design industriel"),
    Metier("H1209", "Intervention technique en études et développement électronique"),
    Metier("H2206", "Réalisation de menuiserie bois et tonnellerie"),
    Metier("H2401", "Assemblage - montage d'articles en cuirs, peaux"),
    Metier("H2301", "Conduite d'équipement de production chimique ou pharmaceutique"),
    Metier("H2403", "Conduite de machine de fabrication de produits textiles"),
    Metier("H2405", "Conduite de machine de textiles nontissés"),
    Metier("H2406", "Conduite de machine de traitement textile"),
    Metier("H2409", "Coupe cuir, textile et matériaux souples"),
    Metier("H2208", "Réalisation d'ouvrages décoratifs en bois"),
    Metier("H2407", "Conduite de machine de transformation et de finition des cuirs et peaux"),
    Metier("H2505", "Encadrement d'équipe ou d'atelier en matériaux souples"),
    Metier("H2415", "Contrôle en industrie du cuir et du textile"),
    Metier("H2501", "Encadrement de production de matériel électrique et électronique"),
    Metier("H2604", "Montage de produits électriques et électroniques"),
    Metier("H2413", "Préparation de fils, montage de métiers textiles"),
    Metier("H2701", "Pilotage d'installation énergétique et pétrochimique"),
    Metier("H2411", "Montage de prototype cuir et matériaux souples"),
    Metier("H2503", "Pilotage d'unité élémentaire de production mécanique ou de travail des métaux"),
    Metier("H2602", "Câblage électrique et électromécanique"),
    Metier("H2209", "Intervention technique en ameublement et bois"),
    Metier("H2203", "Conduite d'installation de production de panneaux bois"),
    Metier("H2101", "Abattage et découpe des viandes"),
    Metier("H2205", "Première transformation de bois d'oeuvre"),
    Metier("H2201", "Assemblage d'ouvrages en bois"),
    Metier("H1505", "Intervention technique en formulation et analyse sensorielle"),
    Metier("H2207", "Réalisation de meubles en bois"),
    Metier("H2402", "Assemblage - montage de vêtements et produits textiles"),
    Metier("H2404", "Conduite de machine de production et transformation des fils"),
    Metier("H2410", "Mise en forme, repassage et finitions en industrie textile"),
    Metier("H2408", "Conduite de machine d'impression textile"),
    Metier("H2412", "Patronnage - gradation"),
    Metier("H2801", "Conduite d'équipement de transformation du verre"),
    Metier("H2601", "Bobinage électrique"),
    Metier("G1804", "Sommellerie"),
    Metier("G1802", "Management du service en restauration"),
    Metier("H1202", "Conception et dessin de produits électriques et électroniques"),
    Metier("H1208", "Intervention technique en études et conception en automatisme"),
    Metier("H1210", "Intervention technique en études, recherche et développement"),
    Metier("H1207", "Rédaction technique"),
    Metier("H1302", "Management et ingénierie Hygiène Sécurité Environnement -HSE- industriels"),
    Metier("H1403", "Intervention technique en gestion industrielle et logistique"),
    Metier("H1401", "Management et ingénierie gestion industrielle et logistique"),
    Metier("H1503", "Intervention technique en laboratoire d'analyse industrielle"),
    Metier("H1501", "Direction de laboratoire d'analyse industrielle"),
    Metier("G1801", "Café, bar brasserie"),
    Metier("G1701", "Conciergerie en hôtellerie"),
    Metier("G1803", "Service en restauration"),
    Metier("G1703", "Réception en hôtellerie"),
    Metier("H1101", "Assistance et support technique client"),
    Metier("G1604", "Fabrication de crêpes ou pizzas"),
    Metier("G1601", "Management du personnel de cuisine"),
    Metier("H1303", "Intervention technique en Hygiène Sécurité Environnement -HSE- industriel"),
    Metier("H1504", "Intervention technique en contrôle essai qualité en électricité et électronique"),
    Metier("H2102", "Conduite d'équipement de production alimentaire"),
    Metier("H2204", "Encadrement des industries de l'ameublement et du bois"),
    Metier("H2202", "Conduite d'équipement de fabrication de l'ameublement et du bois"),
    Metier("H1404", "Intervention technique en méthodes et industrialisation"),
    Metier("H1402", "Management et ingénierie méthodes et industrialisation"),
    Metier("H1506", "Intervention technique qualité en mécanique et travail des métaux"),
    Metier("H1301", "Inspection de conformité"),
    Metier("H1201", "Expertise technique couleur en industrie"),
    Metier("H1502", "Management et ingénierie qualité industrielle"),
    Metier("G1205", "Personnel d'attractions ou de structures de loisirs"),
    Metier("G1602", "Personnel de cuisine"),
    Metier("G1603", "Personnel polyvalent en restauration"),
    Metier("G1301", "Conception de produits touristiques"),
    Metier("H2502", "Management et ingénierie de production"),
    Metier("H2802", "Conduite d'installation de production de matériaux de construction"),
    Metier("H2803", "Façonnage et émaillage en industrie céramique"),
    Metier("H2804", "Pilotage de centrale à béton prêt à l'emploi, ciment, enrobés et granulats"),
    Metier("H2902", "Chaudronnerie - tôlerie"),
    Metier("I1304", "Installation et maintenance d'équipements industriels et d'exploitation"),
    Metier("J1301", "Personnel polyvalent des services hospitaliers"),
    Metier("J1303", "Assistance médico-technique"),
    Metier("J1305", "Conduite de véhicules sanitaires"),
    Metier("J1201", "Biologie médicale"),
    Metier("J1302", "Analyses médicales"),
    Metier("J1307", "Préparation en pharmacie"),
    Metier("H2913", "Soudage manuel"),
    Metier("H2805", "Pilotage d'installation de production verrière"),
    Metier("H2910", "Moulage sable"),
    Metier("H2904", "Conduite d'équipement de déformation des métaux"),
    Metier("H2908", "Modelage de matériaux non métalliques"),
    Metier("H2912", "Réglage d'équipement de production industrielle"),
    Metier("H2906", "Conduite d'installation automatisée ou robotisée de fabrication mécanique"),
    Metier("H3203", "Fabrication de pièces en matériaux composites"),
    Metier("H3201", "Conduite d'équipement de formage des plastiques et caoutchoucs"),
    Metier("H3302", "Opérations manuelles d'assemblage, tri ou emballage"),
    Metier("H3101", "Conduite d'équipement de fabrication de papier ou de carton"),
    Metier("H3401", "Conduite de traitement d'abrasion de surface"),
    Metier("H3402", "Conduite de traitement par dépôt de surface"),
    Metier("I1101", "Direction et ingénierie en entretien infrastructure et bâti"),
    Metier("H3403", "Conduite de traitement thermique"),
    Metier("I1201", "Entretien d'affichage et mobilier urbain"),
    Metier("I1102", "Management et ingénierie de maintenance industrielle"),
    Metier("I1203", "Maintenance des bâtiments et des locaux"),
    Metier("I1306", "Installation et maintenance en froid, conditionnement d'air"),
    Metier("J1103", "Médecine dentaire"),
    Metier("I1310", "Maintenance mécanique industrielle"),
    Metier("I1501", "Intervention en grande hauteur"),
    Metier("I1308", "Maintenance d'installation de chauffage"),
    Metier("I1603", "Maintenance d'engins de chantier, levage, manutention et de machines agricoles"),
    Metier("I1402", "Réparation de biens électrodomestiques et multimédia"),
    Metier("I1503", "Intervention en milieux et produits nocifs"),
    Metier("I1602", "Maintenance d'aéronefs"),
    Metier("I1303", "Installation et maintenance de distributeurs automatiques"),
    Metier("I1605", "Mécanique de marine"),
    Metier("I1607", "Réparation de cycles, motocycles et motoculteurs de loisirs"),
    Metier("H2603", "Conduite d'installation automatisée de production électrique, électronique et microélectronique"),
    Metier("H2605", "Montage et câblage électronique"),
    Metier("H2414", "Préparation et finition d'articles en cuir et matériaux souples"),
    Metier("H2504", "Encadrement d'équipe en industrie de transformation"),
    Metier("N2201", "Personnel d'escale aéroportuaire"),
    Metier("N2202", "Contrôle de la navigation aérienne"),
    Metier("N2102", "Pilotage et navigation technique aérienne"),
    Metier("N3103", "Navigation fluviale"),
    Metier("N3101", "Encadrement de la navigation maritime"),
    Metier("N4201", "Direction d'exploitation des transports routiers de marchandises"),
    Metier("N3203", "Manutention portuaire"),
    Metier("N4203", "Intervention technique d'exploitation des transports routiers de marchandises"),
    Metier("N4403", "Manoeuvre du réseau ferré"),
    Metier("I1301", "Installation et maintenance d'ascenseurs"),
    Metier("I1305", "Installation et maintenance électronique"),
    Metier("I1601", "Installation et maintenance en nautisme"),
    Metier("I1401", "Maintenance informatique et bureautique"),
    Metier("I1502", "Intervention en milieu subaquatique"),
    Metier("I1307", "Installation et maintenance télécoms et courants faibles"),
    Metier("I1309", "Maintenance électrique"),
    Metier("J1101", "Médecine de prévention"),
    Metier("I1604", "Mécanique automobile et entretien de véhicules"),
    Metier("I1606", "Réparation de carrosserie"),
    Metier("J1202", "Pharmacie"),
    Metier("J1304", "Aide en puériculture"),
    Metier("J1102", "Médecine généraliste et spécialisée"),
    Metier("J1104", "Suivi de la grossesse et de l'accouchement"),
    Metier("M1402", "Conseil en organisation et management d'entreprise"),
    Metier("M1404", "Management et gestion d'enquêtes"),
    Metier("M1502", "Développement des ressources humaines"),
    Metier("M1601", "Accueil et renseignements"),
    Metier("M1608", "Secrétariat comptable"),
    Metier("M1704", "Management relation clientèle"),
    Metier("M1701", "Administration des ventes"),
    Metier("M1606", "Saisie de données"),
    Metier("M1706", "Promotion des ventes"),
    Metier("M1803", "Direction des systèmes d'information"),
    Metier("M1805", "Études et développement informatique"),
    Metier("M1801", "Administration de systèmes d'information"),
    Metier("M1808", "Information géographique"),
    Metier("N1201", "Affrètement transport"),
    Metier("N4401", "Circulation du réseau ferré"),
    Metier("N4301", "Conduite sur rails"),
    Metier("H2901", "Ajustement et montage de fabrication"),
    Metier("H2903", "Conduite d'équipement d'usinage"),
    Metier("H2909", "Montage-assemblage mécanique"),
    Metier("H3102", "Conduite d'installation de pâte à papier"),
    Metier("H2907", "Conduite d'installation de production des métaux"),
    Metier("H2905", "Conduite d'équipement de formage et découpage des matériaux"),
    Metier("H2911", "Réalisation de structures métalliques"),
    Metier("H2914", "Réalisation et montage en tuyauterie"),
    Metier("H3301", "Conduite d'équipement de conditionnement"),
    Metier("H3303", "Préparation de matières et produits industriels (broyage, mélange, ...)"),
    Metier("H3202", "Réglage d'équipement de formage des plastiques et caoutchoucs"),
    Metier("H3404", "Peinture industrielle"),
    Metier("I1202", "Entretien et surveillance du tracé routier"),
    Metier("I1103", "Supervision d'entretien et gestion de véhicules"),
    Metier("I1302", "Installation et maintenance d'automatismes"),
    Metier("N2204", "Préparation des vols"),
    Metier("N3201", "Exploitation des opérations portuaires et du transport maritime"),
    Metier("N4102", "Conduite de transport de particuliers"),
    Metier("N4104", "Courses et livraisons express"),
    Metier("N4101", "Conduite de transport de marchandises sur longue distance"),
    Metier("N2205", "Direction d'escale et exploitation aéroportuaire"),
    Metier("N3202", "Exploitation du transport fluvial"),
    Metier("N3102", "Équipage de la navigation maritime"),
    Metier("J1405", "Optique - lunetterie"),
    Metier("J1403", "Ergothérapie"),
    Metier("J1411", "Prothèses et orthèses"),
    Metier("J1409", "Pédicurie et podologie"),
    Metier("J1407", "Orthoptique"),
    Metier("K1206", "Intervention socioculturelle"),
    Metier("K1101", "Accompagnement et médiation familiale"),
    Metier("K1201", "Action sociale"),
    Metier("K1103", "Développement personnel et bien-être de la personne"),
    Metier("J1501", "Soins d'hygiène, de confort du patient"),
    Metier("K1204", "Médiation sociale et facilitation de la vie en société"),
    Metier("J1506", "Soins infirmiers généralistes"),
    Metier("J1504", "Soins infirmiers spécialisés en bloc opératoire"),
    Metier("K1202", "Éducation de jeunes enfants"),
    Metier("J1502", "Coordination de services médicaux ou paramédicaux"),
    Metier("N4103", "Conduite de transport en commun sur route"),
    Metier("N4105", "Conduite et livraison par tournées sur courte distance"),
    Metier("N4302", "Contrôle des transports en commun"),
    Metier("N4204", "Intervention technique d'exploitation des transports routiers de personnes"),
    Metier("N4202", "Direction d'exploitation des transports routiers de personnes"),
    Metier("N4402", "Exploitation et manoeuvre des remontées mécaniques"),
    Metier("M1810", "Production et exploitation de systèmes d'information"),
    Metier("N1103", "Magasinage et préparation de commandes"),
    Metier("N2203", "Exploitation des pistes aéroportuaires"),
    Metier("K1401", "Conception et pilotage de la politique des pouvoirs publics"),
    Metier("K1502", "Contrôle et inspection des Affaires Sociales"),
    Metier("K1701", "Personnel de la Défense"),
    Metier("K1601", "Gestion de l'information et de la documentation"),
    Metier("L1508", "Prise de son et sonorisation"),
    Metier("M1206", "Management de groupe ou de service comptable"),
    Metier("M1102", "Direction des achats"),
    Metier("M1201", "Analyse et ingénierie financière"),
    Metier("M1301", "Direction de grande entreprise ou d'établissement public"),
    Metier("J1306", "Imagerie médicale"),
    Metier("J1401", "Audioprothèses"),
    Metier("K1102", "Aide aux bénéficiaires d'une mesure de protection juridique"),
    Metier("J1507", "Soins infirmiers spécialisés en puériculture"),
    Metier("J1408", "Ostéopathie et chiropraxie"),
    Metier("J1404", "Kinésithérapie"),
    Metier("J1402", "Diététique"),
    Metier("J1505", "Soins infirmiers spécialisés en prévention"),
    Metier("J1503", "Soins infirmiers spécialisés en anesthésie"),
    Metier("J1412", "Rééducation en psychomotricité"),
    Metier("K1305", "Intervention sociale et familiale"),
    Metier("J1406", "Orthophonie"),
    Metier("J1410", "Prothèses dentaires"),
    Metier("K1203", "Encadrement technique en insertion professionnelle"),
    Metier("K1205", "Information sociale"),
    Metier("K1104", "Psychologie"),
    Metier("K1402", "Conseil en Santé Publique"),
    Metier("K1303", "Assistance auprès d'enfants"),
    Metier("K1302", "Assistance auprès d'adultes"),
    Metier("K1207", "Intervention socioéducative"),
    Metier("K1505", "Protection des consommateurs et contrôle des échanges commerciaux"),
    Metier("K1602", "Gestion de patrimoine culturel"),
    Metier("K1504", "Contrôle et inspection du Trésor Public"),
    Metier("K1503", "Contrôle et inspection des impôts"),
    Metier("K1404", "Mise en oeuvre et pilotage de la politique des pouvoirs publics"),
    Metier("K1501", "Application des règles financières publiques"),
    Metier("K1704", "Management de la sécurité publique"),
    Metier("K1801", "Conseil en emploi et insertion socioprofessionnelle"),
    Metier("K1706", "Sécurité publique"),
    Metier("K1703", "Direction opérationnelle de la défense"),
    Metier("K1902", "Collaboration juridique"),
    Metier("K1904", "Magistrature"),
    Metier("K2104", "Éducation et surveillance au sein d'établissements d'enseignement"),
    Metier("K2107", "Enseignement général du second degré"),
    Metier("K2109", "Enseignement technique et professionnel"),
    Metier("K2112", "Orientation scolaire et professionnelle"),
    Metier("K2303", "Nettoyage des espaces urbains"),
    Metier("K2601", "Conduite d'opérations funéraires"),
    Metier("K2306", "Supervision d'exploitation éco-industrielle"),
    Metier("K2301", "Distribution et assainissement d'eau"),
    Metier("K2402", "Recherche en sciences de l'univers, de la matière et du vivant"),
    Metier("K2502", "Management de sécurité privée"),
    Metier("L1204", "Arts du cirque et arts visuels"),
    Metier("L1302", "Production et administration spectacle, cinéma et audiovisuel"),
    Metier("L1303", "Promotion d'artistes et de spectacles"),
    Metier("L1103", "Présentation de spectacles ou d'émissions"),
    Metier("L1304", "Réalisation cinématographique et audiovisuelle"),
    Metier("L1401", "Sportif professionnel"),
    Metier("L1501", "Coiffure et maquillage spectacle"),
    Metier("L1202", "Musique et chant"),
    Metier("L1502", "Costume et habillage spectacle"),
    Metier("L1503", "Décor et accessoires spectacle"),
    Metier("L1504", "Éclairage spectacle"),
    Metier("L1505", "Image cinématographique et télévisuelle"),
    Metier("L1506", "Machinerie spectacle"),
    Metier("M1203", "Comptabilité"),
    Metier("K1301", "Accompagnement médicosocial"),
    Metier("K1304", "Services domestiques"),
    Metier("K1403", "Management de structure de santé, sociale ou pénitentiaire"),
    Metier("K1405", "Représentation de l'État sur le territoire national ou international"),
    Metier("K2103", "Direction d'établissement et d'enseignement"),
    Metier("K1707", "Surveillance municipale"),
    Metier("K2102", "Coordination pédagogique"),
    Metier("K1903", "Défense et conseil juridique"),
    Metier("K2101", "Conseil en formation"),
    Metier("M1205", "Direction administrative et financière"),
    Metier("M1403", "Études et prospectives socio-économiques"),
    Metier("M1302", "Direction de petite ou moyenne entreprise"),
    Metier("M1501", "Assistanat en ressources humaines"),
    Metier("M1207", "Trésorerie et financement"),
    Metier("M1401", "Conduite d'enquêtes"),
    Metier("M1703", "Management et gestion de produit"),
    Metier("M1604", "Assistanat de direction"),
    Metier("M1603", "Distribution de documents"),
    Metier("M1602", "Opérations administratives"),
    Metier("M1503", "Management des ressources humaines"),
    Metier("M1707", "Stratégie commerciale"),
    Metier("M1802", "Expertise et support en systèmes d'information"),
    Metier("M1605", "Assistanat technique et administratif"),
    Metier("M1804", "Études et développement de réseaux de télécoms"),
    Metier("M1609", "Secrétariat et assistanat médical ou médico-social"),
    Metier("M1705", "Marketing"),
    Metier("M1607", "Secrétariat"),
    Metier("M1702", "Analyse de tendance"),
    Metier("M1807", "Exploitation de systèmes de communication et de commandement"),
    Metier("M1806", "Conseil et maîtrise d'ouvrage en systèmes d'information"),
    Metier("N1101", "Conduite d'engins de déplacement des charges"),
    Metier("N1102", "Déménagement"),
    Metier("M1809", "Information météorologique"),
    Metier("N1104", "Manoeuvre et conduite d'engins lourds de manutention"),
    Metier("N1105", "Manutention manuelle de charges"),
    Metier("N1202", "Gestion des opérations de circulation internationale des marchandises"),
    Metier("K2105", "Enseignement artistique"),
    Metier("K2106", "Enseignement des écoles"),
    Metier("K2110", "Formation en conduite de véhicules"),
    Metier("K2111", "Formation professionnelle"),
    Metier("K2603", "Thanatopraxie"),
    Metier("K2401", "Recherche en sciences de l'homme et de la société"),
    Metier("K2304", "Revalorisation de produits industriels"),
    Metier("K2501", "Gardiennage de locaux"),
    Metier("K2602", "Conseil en services funéraires"),
    Metier("K2503", "Sécurité et surveillance privées"),
    Metier("K2302", "Management et inspection en environnement urbain"),
    Metier("K2202", "Lavage de vitres"),
    Metier("K2201", "Blanchisserie industrielle"),
    Metier("K2108", "Enseignement supérieur"),
    Metier("K2305", "Salubrité et traitement de nuisibles"),
    Metier("K2203", "Management et inspection en propreté de locaux"),
    Metier("K2204", "Nettoyage de locaux"),
    Metier("L1102", "Mannequinat et pose artistique"),
    Metier("L1203", "Art dramatique"),
    Metier("L1101", "Animation musicale et scénique"),
    Metier("L1201", "Danse"),
    Metier("L1301", "Mise en scène de spectacles vivants"),
    Metier("M1204", "Contrôle de gestion"),
    Metier("M1101", "Achats"),
    Metier("L1509", "Régie générale"),
    Metier("L1507", "Montage audiovisuel et post-production"),
    Metier("M1202", "Audit et contrôle comptables et financiers"),
    Metier("K1702", "Direction de la sécurité civile et des secours"),
    Metier("K1901", "Aide et médiation judiciaire"),
    Metier("K1802", "Développement local"),
    Metier("K1705", "Sécurité civile et secours"),
    Metier("A1502", "Podologie animale"),
    Metier("B1302", "Décoration d'objets d'art et artisanaux"),
    Metier("B1401", "Réalisation d'objets en lianes, fibres et brins végétaux"),
    Metier("A1416", "Polyculture, élevage"),
    Metier("B1802", "Réalisation d'articles en cuir et matériaux souples (hors vêtement)"),
    Metier("C1106", "Expertise risques en assurances"),
    Metier("B1101", "Création en arts plastiques"),
    Metier("B1301", "Décoration d'espaces de vente et d'exposition"),
    Metier("B1402", "Reliure et restauration de livres et archives"),
    Metier("B1804", "Réalisation d'ouvrages d'art en fils"),
    Metier("A1504", "Santé animale"),
    Metier("B1806", "Tapisserie - décoration en ameublement"),
    Metier("C1205", "Conseil en gestion de patrimoine financier"),
    Metier("C1302", "Gestion back et middle-office marchés financiers"),
    Metier("B1501", "Fabrication et réparation d'instruments de musique"),
    Metier("B1604", "Réparation - montage en systèmes horlogers"),
    Metier("B1801", "Réalisation d'articles de chapellerie"),
    Metier("B1803", "Réalisation de vêtements sur mesure ou en petite série"),
    Metier("C1101", "Conception - développement produits d'assurances"),
    Metier("C1110", "Souscription d'assurances"),
    Metier("C1201", "Accueil et services bancaires"),
    Metier("C1204", "Conception et expertise produits bancaires et financiers"),
    Metier("B1601", "Métallerie d'art"),
    Metier("B1603", "Réalisation d'ouvrages en bijouterie, joaillerie et orfèvrerie"),
    Metier("B1805", "Stylisme"),
    Metier("B1602", "Réalisation d'objets artistiques et fonctionnels en verre"),
    Metier("C1107", "Indemnisations en assurances"),
    Metier("D1201", "Achat vente d'objets d'art, anciens ou d'occasion"),
    Metier("C1206", "Gestion de clientèle bancaire"),
    Metier("C1401", "Gestion en banque et assurance"),
    Metier("C1501", "Gérance immobilière"),
    Metier("D1402", "Relation commerciale grands comptes et entreprises"),
    Metier("A1101", "Conduite d'engins agricoles et forestiers"),
    Metier("A1205", "Sylviculture"),
    Metier("A1303", "Ingénierie en agriculture et environnement naturel"),
    Metier("A1203", "Aménagement et entretien des espaces verts"),
    Metier("A1204", "Protection du patrimoine naturel"),
    Metier("A1402", "Aide agricole de production légumière ou végétale"),
    Metier("A1414", "Horticulture et maraîchage"),
    Metier("B1201", "Réalisation d'objets décoratifs et utilitaires en céramique et matériaux de synthèse"),
    Metier("A1202", "Entretien des espaces naturels"),
    Metier("A1406", "Encadrement équipage de la pêche"),
    Metier("A1411", "Élevage porcin"),
    Metier("A1401", "Aide agricole de production fruitière ou viticole"),
    Metier("A1404", "Aquaculture"),
    Metier("A1407", "Élevage bovin ou équin"),
    Metier("A1201", "Bûcheronnage et élagage"),
    Metier("A1405", "Arboriculture et viticulture"),
    Metier("N2101", "Navigation commerciale aérienne"),
    Metier("N1302", "Direction de site logistique"),
    Metier("N1301", "Conception et organisation de la chaîne logistique"),
    Metier("N1303", "Intervention technique d'exploitation logistique"),
    Metier("A1301", "Conseil et assistance technique en agriculture et environnement naturel"),
    Metier("A1403", "Aide d'élevage agricole et aquacole"),
    Metier("A1417", "Saliculture"),
    Metier("A1302", "Contrôle et diagnostic technique en agriculture"),
    Metier("A1408", "Élevage d'animaux sauvages ou de compagnie"),
    Metier("B1303", "Gravure - ciselure"),
    Metier("A1410", "Élevage ovin ou caprin"),
    Metier("A1503", "Toilettage des animaux"),
    Metier("B1701", "Conservation et reconstitution d'espèces animales"),
    Metier("A1409", "Élevage de lapins et volailles"),
    Metier("A1412", "Fabrication et affinage de fromages"),
    Metier("A1413", "Fermentation de boissons alcoolisées"),
    Metier("A1501", "Aide aux soins animaux"),
    Metier("D1101", "Boucherie"),
    Metier("D1208", "Soins esthétiques et corporels"),
    Metier("D1209", "Vente de végétaux"),
    Metier("E1103", "Communication"),
    Metier("A1415", "Équipage de la pêche"),
    Metier("C1503", "Management de projet immobilier"),
    Metier("D1212", "Vente en décoration et équipement du foyer"),
    Metier("D1301", "Management de magasin de détail"),
    Metier("E1102", "Écriture d'ouvrages, de livres"),
    Metier("E1302", "Conduite de machines de façonnage routage"),
    Metier("E1308", "Intervention technique en industrie graphique"),
    Metier("E1305", "Préparation et correction en édition et presse"),
    Metier("E1307", "Reprographie"),
    Metier("E1204", "Projection cinéma"),
    Metier("E1205", "Réalisation de contenus multimédias"),
    Metier("D1507", "Mise en rayon libre-service"),
    Metier("E1101", "Animation de site multimédia"),
    Metier("E1301", "Conduite de machines d'impression"),
    Metier("E1401", "Développement et promotion publicitaire"),
    Metier("D1404", "Relation commerciale en vente de véhicules"),
    Metier("D1504", "Direction de magasin de grande distribution"),
    Metier("D1509", "Management de département en grande distribution"),
    Metier("E1303", "Encadrement des industries graphiques"),
    Metier("D1501", "Animation de vente"),
    Metier("D1503", "Management/gestion de rayon produits non alimentaires"),
    Metier("E1107", "Organisation d'évènementiel"),
    Metier("E1201", "Photographie"),
    Metier("E1202", "Production en laboratoire cinématographique"),
    Metier("E1203", "Production en laboratoire photographique"),
    Metier("C1103", "Courtage en assurances"),
    Metier("C1104", "Direction d'exploitation en assurances"),
    Metier("C1203", "Relation clients banque/finance"),
    Metier("D1207", "Retouches en habillement"),
    Metier("C1303", "Gestion de portefeuilles sur les marchés financiers"),
    Metier("D1107", "Vente en gros de produits frais"),
    Metier("D1206", "Réparation d'articles en cuir et matériaux souples"),
    Metier("E1104", "Conception de contenus multimédias"),
    Metier("E1105", "Coordination d'édition"),
    Metier("C1102", "Conseil clientèle en assurances"),
    Metier("C1108", "Management de groupe et de service en assurances"),
    Metier("D1103", "Charcuterie - traiteur"),
    Metier("D1104", "Pâtisserie, confiserie, chocolaterie et glacerie"),
    Metier("C1502", "Gestion locative immobilière"),
    Metier("C1504", "Transaction immobilière"),
  ];
}
